_wandb:
    value:
        cli_version: 0.23.1
        e:
            rhqd44w08cuwrbtur9660ohnsjvltman:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "429495676928"
                        used: "12693680128"
                executable: C:\Users\thari\anaconda3\python.exe
                host: Tharu
                memory:
                    total: "25642057728"
                os: Windows-11-10.0.26100-SP0
                program: H:\AI Course\GNN_PPO\routing-model-2025-gnn-ppo-one_agent\main.py
                python: CPython 3.13.5
                root: H:\AI Course\GNN_PPO\routing-model-2025-gnn-ppo-one_agent
                startedAt: "2026-02-13T13:02:23.974031Z"
                writerId: rhqd44w08cuwrbtur9660ohnsjvltman
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
data_dir:
    value: data_version_3
device:
    value: cpu
embed_dim:
    value: 128
episodes:
    value: 500
log_interval:
    value: 20
lr:
    value: 0.001
max_daily_delivery_time_each_truck:
    value: 24
project_name:
    value: routing-model-2025_data_version_3
run_name:
    value: lr0.001_sd42
seed:
    value: 42
wandb:
    value: true
