[project]
name = "routing-model-2025"
version = "0.1.0"
description = ""
authors = [
    {name = "leonardo",email = "leonardo.torres.altez@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  # Referenciamos los subproyectos como dependencias
    "common-lib",
    "loader-lib",
    "logisticsrl-lib",
    "ortools (>=9.15.6755,<10.0.0)"
]


[tool.poetry]
packages = [
    { include = "common_lib", from = "packages/common-lib/src" },
    { include = "loader_lib", from = "packages/loader-lib/src" },
    { include = "logisticsrl_lib", from = "packages/logisticsrl-lib/src" }
]


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[tool.poetry.dependencies]
# Definimos las rutas locales
common-lib = { path = "packages/common-lib", develop = true }
loader-lib = { path = "packages/loader-lib", develop = true }
logisticsrl-lib = { path = "packages/logisticsrl-lib", develop = true }

[tool.poetry.scripts]
train = "logisticsrl_lib.main:train"
benchmarks = "logisticsrl_lib.compute_benchmarks:train"
benchmarks_2 = "logisticsrl_lib.compute_benchmarks_google_ortools:train"