_wandb:
    value:
        cli_version: 0.23.1
        e:
            ezrxeku3sw8rhkjhkkhykkhguzi1wu2f:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "429495676928"
                        used: "12648316928"
                email: tharini.moorthy@estudiantat.upc.edu
                executable: C:\Users\thari\anaconda3\python.exe
                host: Tharu
                memory:
                    total: "25642057728"
                os: Windows-11-10.0.26100-SP0
                program: H:\AI Course\GNN_VRP\main.py
                python: CPython 3.13.5
                root: H:\AI Course\GNN_VRP
                startedAt: "2026-02-03T12:04:04.992303Z"
                writerId: ezrxeku3sw8rhkjhkkhykkhguzi1wu2f
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
datapath:
    value: data/data_version_2
depot:
    value: 0
device:
    value: cpu
embed_dim:
    value: 128
episodes:
    value: 500
graph_mode:
    value: true
log_interval:
    value: 20
lr:
    value: 0.001
max_steps:
    value: 100
project_name:
    value: logistics-rl-poc
run_name:
    value: default
seed:
    value: 42
truck_id:
    value: 1
wandb:
    value: true
