_wandb:
    value:
        cli_version: 0.23.1
        e:
            js6z1d6mvkn5g4uxzzbibctahgjkt0p9:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "429495676928"
                        used: "12694671360"
                executable: C:\Users\thari\anaconda3\python.exe
                host: Tharu
                memory:
                    total: "25642057728"
                os: Windows-11-10.0.26100-SP0
                program: H:\AI Course\GNN_PPO\routing-model-2025-gnn-ppo-one_agent\main.py
                python: CPython 3.13.5
                root: H:\AI Course\GNN_PPO\routing-model-2025-gnn-ppo-one_agent
                startedAt: "2026-02-16T10:28:41.424389Z"
                writerId: js6z1d6mvkn5g4uxzzbibctahgjkt0p9
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
